//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibHKOSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibHKOSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon50 {
            get {
                object obj = ResourceManager.GetObject("icon50", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon51 {
            get {
                object obj = ResourceManager.GetObject("icon51", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon52 {
            get {
                object obj = ResourceManager.GetObject("icon52", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon53 {
            get {
                object obj = ResourceManager.GetObject("icon53", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon54 {
            get {
                object obj = ResourceManager.GetObject("icon54", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon60 {
            get {
                object obj = ResourceManager.GetObject("icon60", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon61 {
            get {
                object obj = ResourceManager.GetObject("icon61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon62 {
            get {
                object obj = ResourceManager.GetObject("icon62", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon63 {
            get {
                object obj = ResourceManager.GetObject("icon63", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon64 {
            get {
                object obj = ResourceManager.GetObject("icon64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon65 {
            get {
                object obj = ResourceManager.GetObject("icon65", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon70 {
            get {
                object obj = ResourceManager.GetObject("icon70", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon71 {
            get {
                object obj = ResourceManager.GetObject("icon71", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon72 {
            get {
                object obj = ResourceManager.GetObject("icon72", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon73 {
            get {
                object obj = ResourceManager.GetObject("icon73", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon74 {
            get {
                object obj = ResourceManager.GetObject("icon74", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon75 {
            get {
                object obj = ResourceManager.GetObject("icon75", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon76 {
            get {
                object obj = ResourceManager.GetObject("icon76", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon77 {
            get {
                object obj = ResourceManager.GetObject("icon77", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon80 {
            get {
                object obj = ResourceManager.GetObject("icon80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon81 {
            get {
                object obj = ResourceManager.GetObject("icon81", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon82 {
            get {
                object obj = ResourceManager.GetObject("icon82", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon83 {
            get {
                object obj = ResourceManager.GetObject("icon83", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon84 {
            get {
                object obj = ResourceManager.GetObject("icon84", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon85 {
            get {
                object obj = ResourceManager.GetObject("icon85", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon90 {
            get {
                object obj = ResourceManager.GetObject("icon90", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon91 {
            get {
                object obj = ResourceManager.GetObject("icon91", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon92 {
            get {
                object obj = ResourceManager.GetObject("icon92", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] icon93 {
            get {
                object obj = ResourceManager.GetObject("icon93", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;iconDescriptions&quot;:{&quot;50&quot;:[&quot;Sunny&quot;,&quot;陽光充沛&quot;,&quot;阳光充沛&quot;],&quot;51&quot;:[&quot;Sunny Periods&quot;,&quot;間有陽光&quot;,&quot;间有阳光&quot;],&quot;52&quot;:[&quot;Sunny Intervals&quot;,&quot;短暫陽光&quot;,&quot;短暂阳光&quot;],&quot;53&quot;:[&quot;Sunny Periods with A Few Showers&quot;,&quot;間有陽光及幾陣驟雨&quot;,&quot;间有阳光及几阵骤雨&quot;],&quot;54&quot;:[&quot;Sunny Intervals with Showers&quot;,&quot;短暫陽光及有驟雨&quot;,&quot;短暂阳光及有骤雨&quot;],&quot;60&quot;:[&quot;Cloudy&quot;,&quot;多雲&quot;,&quot;多云&quot;],&quot;61&quot;:[&quot;Overcast&quot;,&quot;密雲&quot;,&quot;密云&quot;],&quot;62&quot;:[&quot;Light Rain&quot;,&quot;微雨&quot;,&quot;微雨&quot;],&quot;63&quot;:[&quot;Rain&quot;,&quot;雨&quot;,&quot;雨&quot;],&quot;64&quot;:[&quot;Heavy Rain&quot;,&quot;大雨&quot;,&quot;大雨&quot;],&quot;65&quot;:[&quot;Thunderstorms&quot;,&quot;雷暴&quot;,&quot;雷暴&quot;],&quot;70&quot;:[&quot;Fine ( use only in night-time on 1st of the Lunar Month )&quot;,&quot;天色良好 (只在農曆第一日晚間使用)&quot;,&quot;天色良 [rest of string was tru....
        /// </summary>
        internal static string JSON_iconDesc {
            get {
                return ResourceManager.GetString("JSON_iconDesc", resourceCulture);
            }
        }
    }
}
