version: 2.1
orbs:
  win: circleci/windows@2.2.0
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: dotnet build
  test:
    executor: win/default
    steps:
      - run: dotnet test .\UnitTestProject\UnitTestProject.csproj --results-directory:"." --collect"Code Coverage"
  upload-coverage:
    executor: win/default
    steps:
      - codecov/upload:
        file: find . -type f -name '*.coverage'
workflows:
  build-and-upload:
    jobs:
      - build
      - test
        requires:
          - build
      - upload-coverage:
        requires:
          - build
          - test
