 version: 2.1

 orbs:
  win: circleci/windows@2.2.0
  codecov: codecov/codecov@1.1.1

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet build

   codecov-upload-report:
    executor: win/default

    steps:
      - codecov/upload:
        file: "../UnitTest.dcvr"
